"""add messages table

Revision ID: 3564aec13b78
Revises: 5ddad1f4a444
Create Date: 2023-05-06 17:17:45.223464

"""
# pyright: reportPrivateImportUsage=false
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3564aec13b78"
down_revision = "5ddad1f4a444"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("channel_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    # ### end Alembic commands ###
